name: main
on:
  - push
  - pull_request
  - workflow_dispatch
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20
        id: go
      - name: Code checkout
        uses: actions/checkout@v3
      - name: Test
        run: |
          go test -v ./... -coverprofile=profile.cov -covermode=atomic
          GOARCH=386 go test ./... -coverprofile=profile.cov -covermode=atomic
          go test -v ./... -race
      - name: Build
        run: |
          GOOS=linux go build
          GOOS=darwin go build
          GOOS=freebsd go build
          GOOS=windows go build
          GOARCH=386 go build
      - name: Publish coverage
        run: |
          go install github.com/mattn/goveralls@latest
          goveralls -service="github" -coverprofile=$GITHUB_WORKSPACE/profile.cov
        env:
          COVERALLS_TOKEN: ${{ secrets.CODECOV_TOKEN }}

